# Generated by Django 3.2.5 on 2021-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('event', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
