# Generated by Django 3.2.5 on 2021-07-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenueEvent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
