# Generated by Django 3.2.5 on 2021-07-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='The id of the node', max_length=10)),
                ('loc', models.CharField(help_text='The location of the node', max_length=6)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hum', models.DecimalField(decimal_places=1, max_digits=5)),
                ('light', models.DecimalField(decimal_places=1, max_digits=5)),
                ('snd', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
