# Generated by Django 3.2.5 on 2021-07-12 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CollectData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
