# Generated by Django 3.2.5 on 2021-07-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectData', '0002_data_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='loc',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='node_id',
            field=models.CharField(max_length=10),
        ),
    ]
